displayName=Community Lootshare
author=pk-enjoyer
description=Share your loot with your Party and calculate equal settlement payments.
tags=loot,lootshare,party,group,splits
plugins=com.communitylootshare.LootsharePlugin
build=standard
version=4.0.0-beta.1
